"""
Integration tests: text/bubble overlays composited onto a rendered chapter.

The C++ suite (``tests/lib-unit-tests/test_overlay_anchoring.cpp``) pins the placement arithmetic
against synthetic squares. These pin the same contract through the **whole product**: the real CLI
binary, a real RGBA bubble with anti-aliased edges (``fixtures/overlays/``), and an overlay that has
been round-tripped through the workspace JSON on disk — which is how a GUI will actually hand one to
the library.

The assertion is deliberately byte-exact rather than pixel-sampled. Pages are exactly one slice tall,
so **inserting a page renumbers the chapter without changing any page's pixels**: every slice from the
insert down should reappear under the next name, byte for byte, bubble included. An overlay that stays
at an absolute strip-Y instead of riding its page breaks that equality, which is what the control test
pins — without it, a build that silently stopped resolving anchors would still pass.

Pages are generated by ``helpers.make_solid_png`` (stdlib PNG writer, nothing committed): a flat colour
per page is what makes "which page is this slice?" decidable from a hash.
"""

from __future__ import annotations

import hashlib
import json
import os
import pathlib
import subprocess

import pytest

from helpers import create_workspace, make_solid_png


# ---------------------------------------------------------------------------
# Geometry — one page is exactly one slice, so inserting a page shifts whole slices
# ---------------------------------------------------------------------------

PAGE_W = PAGE_H = 400
BUBBLE = pathlib.Path(__file__).parent / "fixtures" / "overlays" / "caption-box.png"

# Flat page colours, in strip order. The bubble is anchored to page index 2.
PAGE_COLOURS = [(200, 30, 30), (30, 200, 30), (200, 200, 30), (200, 30, 200)]
ANCHOR_PAGE  = "page_002.png"

# Sorts between page_000 and page_001, so it lands at strip index 1 — above the anchor page.
INSERTED_PAGE = "page_000b.png"

# Page-relative placement of the bubble on its page (and, for the control, the absolute strip-Y that
# same spot has before anything is inserted: page 2 starts at 2 × 400).
BUBBLE_X, BUBBLE_Y = 80, 100
BUBBLE_ABSOLUTE_Y  = 2 * PAGE_H + BUBBLE_Y


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _hashes(directory: pathlib.Path) -> list[str]:
    """SHA-256 of every rendered slice, in output order."""
    return [
        hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(directory.glob("output_*.png"))
    ]


def _render(platemaker_bin: pathlib.Path, workspace: pathlib.Path,
            input_dir: pathlib.Path, output_dir: pathlib.Path) -> list[str]:
    """Render *input_dir* into a fresh *output_dir* and return the slice hashes."""
    output_dir.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            str(platemaker_bin), "process",
            "--workspace", str(workspace),
            "--input",     str(input_dir),
            "--output",    str(output_dir),
            "--format",    "png",
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"render failed:\n{result.stderr}"
    hashes = _hashes(output_dir)
    # An unchanged re-render is skipped entirely ("Nothing to do"), leaving the directory empty. That
    # would silently turn a comparison into a comparison of nothing, so make it loud instead.
    assert hashes, f"render wrote no slices — it was a no-op:\n{result.stderr}"
    return hashes


def _set_overlay(workspace: pathlib.Path, *, anchor_to: str | None, y: int) -> None:
    """
    Put a single bubble on the project, anchored to *anchor_to* (a page filename) or absolute.

    Written straight into the workspace JSON because the CLI has no overlay command — overlays are
    authored by a GUI. That makes this a test of the persisted contract too: the same keys a consumer
    writes are the ones the render reads back.
    """
    data    = json.loads(workspace.read_text())
    project = data["projectItems"][0]

    anchor_uid = ""
    if anchor_to is not None:
        anchor_uid = next(
            f["uid"] for f in project["inputFiles"]
            if os.path.basename(f["filePath"]) == anchor_to
        )

    project["stripOverlays"] = [{
        "uid":            "ovl-caption",
        "assetPath":      str(BUBBLE.resolve()),
        "sha256":         "",
        "anchorInputUid": anchor_uid,
        "x":              BUBBLE_X,
        "y":              y,
        "enabled":        True,
        "blend":          "Over",
    }]
    workspace.write_text(json.dumps(data, indent=2))


def _rescan_inputs(platemaker_bin: pathlib.Path, workspace: pathlib.Path,
                   project: str, input_dir: pathlib.Path) -> None:
    """Pick up a file added to the input directory (``process`` alone only re-scans on create)."""
    result = subprocess.run(
        [
            str(platemaker_bin), "project", "mod",
            "--workspace", str(workspace),
            "--name",      project,
            "--input",     str(input_dir),
        ],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, f"project mod failed:\n{result.stderr}"


@pytest.fixture()
def chapter(platemaker_bin: pathlib.Path, tmp_workspace: pathlib.Path):
    """
    A four-page chapter rendered once with no overlays, ready for a bubble and an inserted page.

    Returns ``(workspace, input_dir, project_name, plain_hashes)`` — the hashes being the overlay-free
    baseline a test locates its bubble against. It comes from this first render rather than a second
    one because an unchanged re-render is skipped and would write nothing.
    """
    input_dir = tmp_workspace / "in"
    input_dir.mkdir()
    for i, colour in enumerate(PAGE_COLOURS):
        make_solid_png(input_dir / f"page_{i:03d}.png", PAGE_W, PAGE_H, *colour)

    workspace = tmp_workspace / "chapter.platemaker.json"
    create_workspace(platemaker_bin, workspace, target_width=PAGE_W, slice_height=PAGE_H)

    # This render registers the project (and mints the input uids the overlay anchors to) as well as
    # producing the overlay-free reference.
    plain = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "plain")
    return workspace, input_dir, input_dir.name, plain


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_anchored_bubble_rides_its_page_when_a_page_is_inserted_above(
    platemaker_bin: pathlib.Path,
    tmp_workspace:  pathlib.Path,
    chapter,
) -> None:
    """
    Inserting a page renumbers the chapter and changes nothing else — the bubble included.

    This is the property the whole feature exists for: an author who adds a page at the front does not
    have to go back and re-place every bubble below it.
    """
    workspace, input_dir, project, plain = chapter

    _set_overlay(workspace, anchor_to=ANCHOR_PAGE, y=BUBBLE_Y)
    before = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "before")
    assert len(before) == len(PAGE_COLOURS)

    # The bubble must be on the page it was anchored to, and on no other. Checking only that the
    # chapter shifts cleanly is not enough: a build that ignored the anchor and read the page-relative
    # y as a strip-Y would drop the bubble near the top of the chapter — above the insert, where
    # nothing moves — and shift just as cleanly.
    assert [i for i in range(len(plain)) if before[i] != plain[i]] == [2], (
        "the bubble should have changed page 2's slice and nothing else"
    )

    make_solid_png(input_dir / INSERTED_PAGE, PAGE_W, PAGE_H, 30, 200, 200)
    _rescan_inputs(platemaker_bin, workspace, project, input_dir)
    after = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "after")

    assert len(after) == len(before) + 1, "the inserted page should add exactly one slice"
    assert after[0] == before[0], "the page above the insert must not move"
    assert after[2:] == before[1:], (
        "every page from the insert down should be the same pixels one slice lower — a mismatch here "
        "means the bubble stayed behind while its page moved"
    )


def test_unanchored_bubble_keeps_its_strip_y_and_is_left_behind(
    platemaker_bin: pathlib.Path,
    tmp_workspace:  pathlib.Path,
    chapter,
) -> None:
    """
    The control: an overlay with no anchor is absolute by definition, and absolute means it drifts.

    Pinning the drift is what gives the test above its meaning — both would pass vacuously if the
    render had quietly stopped composing overlays at all.
    """
    workspace, input_dir, project, plain = chapter

    _set_overlay(workspace, anchor_to=None, y=BUBBLE_ABSOLUTE_Y)
    before = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "before")

    make_solid_png(input_dir / INSERTED_PAGE, PAGE_W, PAGE_H, 30, 200, 200)
    _rescan_inputs(platemaker_bin, workspace, project, input_dir)
    after = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "after")

    assert after[2:] != before[1:], (
        "an unanchored overlay must stay at its strip-Y, which after an insert is a different page"
    )


def test_overlay_config_alone_forces_a_re_render(
    platemaker_bin: pathlib.Path,
    tmp_workspace:  pathlib.Path,
    chapter,
) -> None:
    """
    Moving a bubble changes no input and no output file, so only the processing signature can catch it.

    Without that fold into staleness the render would report "nothing to do" and the author would keep
    looking at the old bubble position.
    """
    workspace, input_dir, project, plain = chapter

    _set_overlay(workspace, anchor_to=ANCHOR_PAGE, y=BUBBLE_Y)
    first = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "first")

    _set_overlay(workspace, anchor_to=ANCHOR_PAGE, y=BUBBLE_Y + 40)
    moved = _render(platemaker_bin, workspace, input_dir, tmp_workspace / "moved")

    assert moved != first, "a moved bubble must re-render its slice"
    assert moved[0] == first[0], "pages the bubble never touched must stay byte-identical"
